name: ble_train_controller
description: BLE蓝牙遥控火车控制器 - 工业仪表盘风格
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true